name: Validate Branch Name

on:
pull_request:
types:
  - opened
  - edited
  - synchronize

jobs:
validate-branch-name:
runs-on: ubuntu-latest
  
  ```
steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Validate Branch Name
    run: |
      echo "Validating branch name..."
      branch_name=${{ github.head_ref }}
      
      # Allowed format:
      # (fix|release|feat|hotfix|refactor|build|test|feature)/
      # {letters(1-3)}-{number}-{slug}
      
      pattern='^(fix|release|feat|hotfix|refactor|build|test|feature)\/[A-Za-z]{1,3}-[0-9]+-[a-z0-9-]+$'
      
      if [[ "$branch_name" =~ $pattern ]]; then
        echo "✅ Branch name '$branch_name' is valid."
      else
        echo "❌ Branch name '$branch_name' is invalid. Please use the format:"
        echo "  {type}/ABC-123-description"
        echo "Examples:"
        echo "  feature/SF-16-login"
        echo "  fix/fta-1-crash"
        echo "  hotfix/Ab-123-fix-login-crash"
        exit 1
      fi
